name: cabal

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]
  schedule:
    - cron: "00 15 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ["8.6", "8.8", "8.10", "9.0"]
        cabal: ["3.2"]
        cache-version: ["2021-05-21"]

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache ~/.cabal/store
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cache-version }}-cabal

    - name: Install dependencies
      run: |
        cabal update
        cabal configure --disable-optimization --enable-tests --write-ghc-environment-files=always -j2
        cabal build --only-dependencies

    - name: Build & Test
      run: |
        cabal build --flag dev
        cabal test --flag dev
